<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>OFDCompose.CorpusDocxGenerator</RootNamespace>
    <AssemblyName>OFDCompose.CorpusDocxGenerator</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" />
  </ItemGroup>

</Project>
