"""Generate the WP0.4 candidate repertoire; never run during normal builds/tests.

GB 2312's complete 7445-character mapping comes from Python's gb2312 codec.
All runtime decisions use the committed table, not a platform codec or ICU.
"""

import hashlib
from pathlib import Path

points = set()
for first in range(0xA1, 0xF8):
    for second in range(0xA1, 0xFF):
        try:
            points.add(ord(bytes([first, second]).decode("gb2312")))
        except UnicodeDecodeError:
            pass
assert len(points) == 7445

# ASCII, Latin-1/Extended A+B, combining marks, Latin Extended Additional,
# CJK Unified Ideographs (including GBK's Han additions) and extensions A/B.
for start, end in [
    (0x20, 0x7E), (0xA0, 0x24F), (0x300, 0x36F), (0x1E00, 0x1EFF),
    (0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0x20000, 0x2A6DF),
]:
    points.update(range(start, end + 1))
# Additional business symbols: euro and mathematical minus.
points.update([0x20AC, 0x2212])

ranges = []
for point in sorted(points):
    if ranges and point == ranges[-1][1] + 1:
        ranges[-1][1] = point
    else:
        ranges.append([point, point])

# Hash the sorted scalar list, each value encoded as unsigned big-endian uint32.
digest = hashlib.sha256(b"".join(p.to_bytes(4, "big") for p in sorted(points))).hexdigest()
output = "// Generated by tools/update-repertoire.py; review every repertoire change.\n"
output += f'export const repertoireSha256 = "{digest}";\n'
output += f"export const repertoireCodePointCount = {len(points)};\n"
output += "export const repertoireRanges: readonly (readonly [number, number])[] = [\n"
output += "".join(f"  [0x{start:x}, 0x{end:x}],\n" for start, end in ranges)
output += "];\n"
Path(__file__).resolve().parents[1].joinpath("src/repertoire-data.ts").write_text(output)
