<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <ProjectReference Include="../../src/OFDCompose.OfdIrWriter/OFDCompose.OfdIrWriter.csproj" />
    <ProjectReference Include="../../../third_party/ofdrw.net/src/Ofdrw.Net.Reader/Ofdrw.Net.Reader.csproj" />
  </ItemGroup>
</Project>
